build-PythonExtensionLayer:
	cp -r extensions $(ARTIFACTS_DIR)
	cp -r python-extension $(ARTIFACTS_DIR)
	python -m pip install -r python-extension/requirements.txt -t $(ARTIFACTS_DIR)/python-extension
